### ISSUE TITLE
Directive doesn't work after updating angular2 to rc.4

### ISSUE THREAD

**Issue by deniskrishna** [mattlewis92/angular2-bootstrap-confirm#16]
Hello! After updating angular to rc.4 directive doesn't seem to work. I get the following error:

`
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'message' since it isn't a known native property ("
            mwlСonfirm
            [title]="title"
            [ERROR ->][message]="message"
            (confirm)="deleteMilestone()"
            (cancel)="cancelClicked
`

I've seen similar issues, but dont understand, how to fix this.
Current version is 0.8.1.
Thanks!

**Comment by mattlewis92** [comment]
That normally happens when angular isn't picking up the `mwlСonfirm` directive, so doesn't know about the `[message]="message"` input and thinks it's a native property (which it's not of a button, hence the error). I think you're missing `directives: [Confirm]` on your components decorator metadata 😄

**Comment by deniskrishna** [comment]
i also thought i made a mistake and forgot to add a directive, but no.
here is my component:
`@Component({
    selector: 'milestones',  
    directives: [MarkdownComponent, Confirm],  
    providers: [ConfirmOptions,
        provide(Position, {
            useClass: PositionService
        })],
    precompile: [
        ConfirmPopover
    ],
    template
})`

**Comment by mattlewis92** [comment]
It might be the deprecated `provide()`?
```
@Component({
    selector: 'milestones',  
    directives: [Confirm],  
    providers: [
      ConfirmOptions,
      {provide: Position, useClass: PositionService}
    ],
    precompile: [
        ConfirmPopover
    ],
    template
})
```

**Comment by deniskrishna** [comment]
actually, when i install this package via npm, i got different modules, for example, in confirm.directive i dont even have @directive decorator. strange thing.
