### ISSUE TITLE
Not working on div with overflow:auto

### ISSUE THREAD

**Issue by delike** [mattlewis92/angular2-bootstrap-confirm#17]
Hi,
the popover is not working when it is an a small div with overflow:auto

The solutions on this Topic won't work:
https://github.com/twbs/bootstrap/issues/5889

On the Screenshot you can see the problem. The Code is the following:

`<div class="panel panel-primary">
                <div class="panel-body">
                    <b>Ansprechpartner:</b><br/>
                    <p-accordion [multiple]="true" *ngIf="selectedKunde.ansprechpartners">
                        <p-accordionTab *ngFor="let ansprechpartner of selectedKunde.ansprechpartners">
                            <header>
                                {{ansprechpartner.name}}
                            </header>
                            <div class="col-xs-12">
                                <form class="form-horizontal" (keyup)="showAnsprechpartnerButtons[ansprechpartner.id] = true">
                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button
                                                    class="btn btn-xs btn-danger"
                                                    data-container="body"
                                                    mwlConfirm
                                                    [title]="'Achtung'"
                                                    [message]="'Ansprechpartner wirklich löschen?'"
                                                    placement="top"
                                                    [confirmText]="'Ja'"
                                                    [cancelText]="'Nein'"
                                                    (confirm)="deleteAnsprechpartner(ansprechpartner)"
                                                    [(isOpen)]="isOpen[ansprechpartner.id]">Löschen
                                            </button>
                                            <div class="btn-group pull-right" *ngIf="showAnsprechpartnerButtons[ansprechpartner.id]">
                                                <button class="btn btn-xs btn-info" (click)="cancelEditAnsprechpartner(ansprechpartner.id)">Abbrechen</button>
                                                <button class="btn btn-xs btn-success" (click)="saveEditAnsprechpartner(ansprechpartner.id)">Speichern</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </p-accordionTab>
                    </p-accordion>
                </div>
            </div>
`

![bildschirmfoto 2016-07-14 um 09 37 57](https://cloud.githubusercontent.com/assets/16492150/16831697/aefedaa4-49a6-11e6-8fd5-e38d6103db84.png)

**Comment by mattlewis92** [comment]
Try:
```
[appendToBody]="true"
```
