### ISSUE TITLE
WARNING: sanitizing

### ISSUE THREAD

**Issue by delike** [mattlewis92/angular2-bootstrap-confirm#18]
Hi,

the Module is working but since rc4 i got the following warning on load and click:

WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

**Comment by delike** [comment]
it is just when i use umlauts like "äüö" on message-string

**Comment by mattlewis92** [comment]
It's an issue with angular with no known workaround atm, it's just a warning so you can ignore it safely: https://github.com/angular/angular/issues/9392#issuecomment-232069535
