### ISSUE TITLE
Cannot read property 'visitStatement' of undefined

### ISSUE THREAD

**Issue by lacroixdavid1** [mattlewis92/angular2-bootstrap-confirm#19]
Hello i'm getting this error when using your component : 

> VM260814:84 EXCEPTION: TypeError: Cannot read property 'visitStatement' of undefined

any ideas on what is causing this ?

thx a lot

**Comment by mattlewis92** [comment]
Looks like an error with your config somewhere, googling the error I found this which might help: http://stackoverflow.com/questions/37165992/angular-2-exception-typeerror-cannot-read-property-isskipself-of-null-brow
