### ISSUE TITLE
Dependency on core-js typings

### ISSUE THREAD

**Issue by deniskrishna** [mattlewis92/angular2-bootstrap-confirm#20]
Is it possible to remove dependency on @types/core-js?
I'm updated angular2 to 2.0.0 and removed core-js typings, because of setting lib option in compilerOptions of tsconfig.json, so corejs provided by typescript by default.

Without this typing i get the following error:
`confirmOptions.provider.d.ts:1:0
Cannot find type definition file for 'core-js'.`

**Comment by mattlewis92** [comment]
That's odd, there's no import of core-js in the source code, I will do some digging and see if I can work out what's going on. Also are you on 1.0.1 of the library?

**Comment by deniskrishna** [comment]
Yes, i install 1.0.1 version of the library. After removing by hand reference path to core-js from `confirmOptions.provider.d.ts` everything seems working fine.

**Comment by mattlewis92** [comment]
Ah worked out what was going on, it was simple enough to fix. I will cut a release in a few hours as soon as I have decent wifi

**Comment by mattlewis92** [comment]
Fixed in 1.0.2, thanks for reporting! 😄

**Comment by deniskrishna** [comment]
Thanks for such a quick response!
