### ISSUE TITLE
Help required  angular2-bootstrap-confirm CSS

### ISSUE THREAD

**Issue by waqarhabib** [mattlewis92/angular2-bootstrap-confirm#21]
Matt Lewis, Thanks for such a nice control. 
Using your angular2-bootstrap-confirm dialog I want to change its css but unable to do that, or I want to remove the CSS the dialog have what I have to do. Help required

**Comment by mattlewis92** [comment]
There is no CSS on the popover, only the bootstrap classes. If you're not using bootstrap you can easily write your own CSS to style the popover that targets the components classes.
